vscode:
  extensions:
    - Zignd.html-css-class-completion@1.19.0:b3YWQQIEP1z3u93nyLX0UA==
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==
    - esbenp.prettier-vscode@3.18.0:SpDMXXww8cAUOXaBCNECgQ==
    - steoates.autoimport@1.5.3:ssEPucpXsRjqSbJX1bW0YA==
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - formulahendry.auto-rename-tag@0.1.1:lKCmLIZAiCM0M8AjDnwCLQ==
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.3:MioHhlbqHKgivweg8MqHrA==
    - dbaeumer.vscode-eslint@2.0.14:1tvpqBPuBjXKFKOYCZ5n/A==
    - aaron-bond.better-comments@2.0.5:YKNfOclR4e8XAxlj4xp2AA==
    - alexiv.vscode-angular2-files@1.6.2:FWRDYYIh9NqVBX/S0KQ/Rw==